### ISSUE TITLE
再提一个优化的建议

### ISSUE THREAD

**Issue by zhen-lit** [Zws-China/DatePicker#12]
当时间选择小于当前的时间就自动滚动回到当前这个时间节点上，比如：2017-11-15 10:20
选择2015小于当前时间2017就自动回滚到2017上

**Comment by Zws-China** [comment]
可以设置最小日期，当滚动的日期小于设置的最小日期，就会自动回滚至最小设置日期。
    NSDateFormatter *minDateFormater = [[NSDateFormatter alloc] init];
    [minDateFormater setDateFormat:@"yyyy-MM-dd HH:mm"];
    NSDate *minDate = [minDateFormater dateFromString:@"2017-11-15 10:20"];
    [datepicker setMinLimitDate:minDate];
