### ISSUE TITLE
设置了最大最小时间期限，6s ,11.1版本的手机滑动会因为数组越界闪退，估计问题在_yearArray[yearIndex]这个上面，具体的怎么出现的不知道，测试出现较少

### ISSUE THREAD

**Issue by sngrui** [Zws-China/DatePicker#15]
*** -[__NSArrayM objectAtIndexedSubscript:]: index 18446744073709549746 beyond bounds [0 .. 199]

**Comment by XFCoding** [comment]
我也出现这个问题了，而且，crash在日益增多
