### ISSUE TITLE
其他样式报错

### ISSUE THREAD

**Issue by HongxiangShe** [Zws-China/DatePicker#2]
除了 DateStyleShowYearMonthDayHourMinute  样式, 其他样式都报错

**Comment by Zws-China** [comment]
请加上   datepicker.minLimitDate = [NSDate date:@"1970-1-01 00:00" WithFormat:@"yyyy-MM-dd HH:mm"];
    datepicker.maxLimitDate = [NSDate date:@"2049-12-31 23:59" WithFormat:@"yyyy-MM-dd HH:mm"];
两句，设置最大和最小日期就不会崩溃

**Comment by HongxiangShe** [comment]
设置小于datepicker.minLimitDate小于1970不起作用

**Comment by Zws-China** [comment]
请下载最新版本的Demo，我做了修改。你说的功能都已经基本实现
https://github.com/Zws-China/DatePicker
