### ISSUE TITLE
佛历都不支持，玩个卵

### ISSUE THREAD

**Issue by jianjianjianjian** [Zws-China/DatePicker#26]
佛历都不支持，玩个卵

**Comment by koploop** [comment]
> 佛历都不支持，玩个卵

伸手党。开源，不是定制。有能耐自己提交PR, 没能耐还BB.

**Comment by jianjianjianjian** [comment]
> > 佛历都不支持，玩个卵
> 
> 伸手党。开源，不是定制。有能耐自己提交PR, 没能耐还BB.

早已写完，让你失望了，写个UI要什么能耐？

**Comment by Zws-China** [comment]
你好，我这个demo现在是不支持佛历哈。推荐你看看别人写的这个https://github.com/WenchaoD/FSCalendar     写得非常好。

**Comment by lucky-ding** [comment]
> > > 佛历都不支持，玩个卵
> > 
> > 
> > 伸手党。开源，不是定制。有能耐自己提交PR, 没能耐还BB.
> 
> 早已写完，让你失望了，写个UI要什么能耐？

写完了你来这说个蛋蛋。
