### ISSUE TITLE
能否增加功能

### ISSUE THREAD

**Issue by zhuguoliang1014** [Zws-China/DatePicker#27]
1.设置分钟间隔
2.设置每天的开始时间（比如，每天只显示早8—晚8）

**Comment by Zws-China** [comment]
不好意思，这个框架没有设置分钟间隔的功能。
如果你需要，可以修改WSDatePickerView.m中第218行源码中代码为下面这段。
for (int i=0; i<60; i++) {
        NSString *num = [NSString stringWithFormat:@"%02d",i];
        if (0<i && i<=12)
            [_monthArray addObject:num];
        if (i<24)
            [_hourArray addObject:num];
        if (i%5 == 0) 
            [_minuteArray addObject:num];
    }

其中(i%5 == 0) 的5就是分钟间隔。

**Comment by Zws-China** [comment]
设置早8到晚8就将_ hourArray里面的元素改成8到20就行。

**Comment by zhuguoliang1014** [comment]
嗯嗯，我修改过了。谢谢哈
    	
    	

    	获取 Outlook for iOS
    
  




On Tue, Nov 6, 2018 at 2:44 PM +0800, "Zws" <notifications@github.com> wrote:












不好意思，这个框架没有设置分钟间隔的功能。

如果你需要，可以修改WSDatePickerView.m中第218行源码中代码为下面这段。

for (int i=0; i<60; i++) {

NSString *num = [NSString stringWithFormat:@"%02d",i];

if (0<i && i<=12)

[_monthArray addObject:num];

if (i<24)

[_hourArray addObject:num];

if (i%5 == 0)

[_minuteArray addObject:num];

}


其中(i%5 == 0) 的5就是分钟间隔。

**Comment by zhuguoliang1014** [comment]
嗯嗯，都处理好了。嘻嘻
    	
    	

    	获取 Outlook for iOS
    
  




On Tue, Nov 6, 2018 at 2:46 PM +0800, <caimter@163.com> wrote:













  
  
  
    
    	嗯嗯，我修改过了。谢谢哈
    	
    	

    	获取 Outlook for iOS
    
  




On Tue, Nov 6, 2018 at 2:44 PM +0800, "Zws" <notifications@github.com> wrote:












不好意思，这个框架没有设置分钟间隔的功能。

如果你需要，可以修改WSDatePickerView.m中第218行源码中代码为下面这段。

for (int i=0; i<60; i++) {

NSString *num = [NSString stringWithFormat:@"%02d",i];

if (0<i && i<=12)

[_monthArray addObject:num];

if (i<24)

[_hourArray addObject:num];

if (i%5 == 0)

[_minuteArray addObject:num];

}


其中(i%5 == 0) 的5就是分钟间隔。
