### ISSUE TITLE
分钟支持间隔 00 05 10 15

### ISSUE THREAD

**Issue by wasterd** [Zws-China/DatePicker#28]
分钟支持间隔 00 05 10 15 20 25 30 35 40 45 50 55 这种方式设置后崩溃

**Comment by Zws-China** [comment]
不好意思，这个框架没有设置分钟间隔的功能。
如果你需要，可以修改WSDatePickerView.m中第218行源码中代码为下面这段。
for (int i=0; i<60; i++) {
NSString *num = [NSString stringWithFormat:@"%02d",i];
if (0<i && i<=12)
[_monthArray addObject:num];
if (i<24)
[_hourArray addObject:num];
if (i%5 == 0)
[_minuteArray addObject:num];
}

其中(i%5 == 0) 的5就是分钟间隔。
