### ISSUE TITLE
只有年月，选择2月，不会反回值

### ISSUE THREAD

**Issue by songgp** [Zws-China/DatePicker#29]

**Comment by Zws-China** [comment]
你好，我这边使用正常，无法复现此问题。能否将你的代码块发给我看看？联系我的QQ：784846767

WSDatePickerView *datepicker = [[WSDatePickerView alloc] initWithDateStyle:DateStyleShowYearMonth CompleteBlock:^(NSDate *selectDate) {
    NSString *dateString = [selectDate stringWithFormat:@"yyyy-MM"];
    NSLog(@"选择的日期：%@",dateString);
}];
[datepicker show];

**Comment by songgp** [comment]
把手机当前日期调到一月31号，在设置成DateStyleShowYearMonth，，，在选择2月，即可复现

**Comment by Zws-China** [comment]
谢谢你提醒，我这边做了修改，你重新下载就可以了。
