### ISSUE TITLE
选择年月 2月不回返回值？？？？？？

### ISSUE THREAD

**Issue by a463544811** [Zws-China/DatePicker#30]

**Comment by Zws-China** [comment]
你好，我无法复现此问题。能否将你的代码块发给我看看？联系我的QQ：784846767

WSDatePickerView *datepicker = [[WSDatePickerView alloc] initWithDateStyle:DateStyleShowYearMonth CompleteBlock:^(NSDate *selectDate) {
    NSString *dateString = [selectDate stringWithFormat:@"yyyy-MM"];
    NSLog(@"选择的日期：%@",dateString);
}];
[datepicker show];

**Comment by songgp** [comment]
你把手机当前日期设置到，1月31号，在选择年月，选择2月

**Comment by Zws-China** [comment]
谢谢你提醒，我这边做了修改，你重新下载就可以了。
