### ISSUE TITLE
pod后 init报错  引用xib闪退

### ISSUE THREAD

**Issue by Zhaoxinak** [Zws-China/DatePicker#35]
self = [[[NSBundle mainBundle] loadNibNamed:NSStringFromClass([self class]) owner:self options:nil] lastObject];

改成以下就好

self = [[[NSBundle bundleForClass:[self class]] loadNibNamed:NSStringFromClass([self class]) owner:self options:nil] lastObject];

**Comment by Zws-China** [comment]
谢谢

**Comment by byteboy-dev** [comment]
没用

**Comment by byztl** [comment]
在Build Phases -> Copy bundle resources 里引入xib文件可以解决
