### ISSUE TITLE
模拟器运行报错,真机还没试

### ISSUE THREAD

**Issue by qiuyan81** [Zws-China/DatePicker#37]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/mypc/Library/Developer/CoreSimulator/Devices/79C779D8-2B95-4710-9ECB-62DA97F292D8/data/Containers/Bundle/Application/04EA0384-1013-4CF4-B429-5A8F745547D9/myapp.app> (loaded)' with name 'WSDatePickerView''

**Comment by ieliwb** [comment]
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/mypc/Library/Developer/CoreSimulator/Devices/79C779D8-2B95-4710-9ECB-62DA97F292D8/data/Containers/Bundle/Application/04EA0384-1013-4CF4-B429-5A8F745547D9/myapp.app> (loaded)' with name 'WSDatePickerView''
大佬解决了吗？我模拟器也是点击就崩了
