### ISSUE TITLE
现在bug还修复吗？还有没有人维护？

### ISSUE THREAD

**Issue by qiuyan81** [Zws-China/DatePicker#41]
-(void)dismiss {
    [UIView animateWithDuration:.3 animations:^{
        self.bottomConstraint.constant = -self.height;//ios13这行报错了 还能修复吗？
        self.backgroundColor = RGBA(0, 0, 0, 0);
        [self layoutIfNeeded];
    } completion:^(BOOL finished) {
        [self.subviews makeObjectsPerformSelector:@selector(removeFromSuperview)];
        [self removeFromSuperview];
    }];
}

**Comment by Zws-China** [comment]
你好，我这边试了，没有报错。你发一下错误信息我分析一下。
