### ISSUE TITLE
超级大的bug

### ISSUE THREAD

**Issue by hjw472015868** [Zws-China/DatePicker#7]
楼主, 你这个有一个非常大的bug, 百分之百的重现, 就是当你选择的style为月日, 或者月日时分, 这两种格式的时候, 天数选择的是31天的月份 ,  然后在把月份滑到不是31天的月份, 就崩溃了,  我相信你自己也知道这个问题吧

**Comment by Zws-China** [comment]
好的，谢谢提醒，这个我稍后改过来。

**Comment by Zws-China** [comment]
你好，问题已经解决，https://github.com/Zws-China/DatePicker
